logging:
  level:
    org:
      springframework: ERROR

management:
  endpoint:
    beans:
      enabled: true
    metrics:
      enabled: true
    health:
      showDetails: "always"
  server:
    port: 9005
    servlet:
      contextPath: "/api/v1/cities/"
  endpoints:
    web:
      exposure:
        include: "*"